-- MySQL Script generated by MySQL Workbench
-- Tue Nov  8 09:43:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `ID` INT NOT NULL,
  `Location` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cart` (
  `item` VARCHAR(45) NOT NULL,
  `total weight` INT NULL,
  PRIMARY KEY (`item`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `ID` INT NOT NULL,
  `studentID` VARCHAR(45) NULL,
  `Items` VARCHAR(45) NULL,
  `student_ID` INT NOT NULL,
  `cart_item` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_order_student1_idx` (`student_ID` ASC) VISIBLE,
  INDEX `fk_order_cart1_idx` (`cart_item` ASC) VISIBLE,
  CONSTRAINT `fk_order_student1`
    FOREIGN KEY (`student_ID`)
    REFERENCES `mydb`.`student` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_cart1`
    FOREIGN KEY (`cart_item`)
    REFERENCES `mydb`.`cart` (`item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `ID` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`robot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`robot` (
  `ID` INT NOT NULL,
  `orderID` VARCHAR(45) NULL,
  `destination` VARCHAR(45) NULL,
  `status` INT NULL,
  `order_ID` INT NOT NULL,
  `employee_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `order_ID`),
  INDEX `fk_robot_order1_idx` (`order_ID` ASC) VISIBLE,
  INDEX `fk_robot_employee1_idx` (`employee_ID` ASC) VISIBLE,
  CONSTRAINT `fk_robot_order1`
    FOREIGN KEY (`order_ID`)
    REFERENCES `mydb`.`order` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_robot_employee1`
    FOREIGN KEY (`employee_ID`)
    REFERENCES `mydb`.`employee` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`items` (
  `item` VARCHAR(45) NOT NULL,
  `weight` INT NULL,
  `descrip` VARCHAR(45) NULL,
  `cart_item` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`item`),
  INDEX `fk_items_cart1_idx` (`cart_item` ASC) VISIBLE,
  CONSTRAINT `fk_items_cart1`
    FOREIGN KEY (`cart_item`)
    REFERENCES `mydb`.`cart` (`item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
