-- MySQL Script generated by MySQL Workbench
-- Tue Nov 15 10:07:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema u413142534_jaysnest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema u413142534_jaysnest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `u413142534_jaysnest` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `u413142534_jaysnest` ;

-- -----------------------------------------------------
-- Table `u413142534_jaysnest`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u413142534_jaysnest`.`student` (
  `ID` INT(11) NOT NULL,
  `Location` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `u413142534_jaysnest`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u413142534_jaysnest`.`order` (
  `ID` INT(11) NOT NULL,
  `studentID` VARCHAR(45) NULL DEFAULT NULL,
  `Items` VARCHAR(45) NULL DEFAULT NULL,
  `student_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_order_student1_idx` (`student_ID` ASC) VISIBLE,
  CONSTRAINT `fk_order_student1`
    FOREIGN KEY (`student_ID`)
    REFERENCES `u413142534_jaysnest`.`student` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `u413142534_jaysnest`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u413142534_jaysnest`.`cart` (
  `item` VARCHAR(45) NULL DEFAULT NULL,
  `total weight` INT(11) NULL DEFAULT NULL,
  `cartID` INT(11) NOT NULL,
  `order_ID` INT(11) NOT NULL,
  PRIMARY KEY (`cartID`),
  INDEX `fk_cart_order1_idx` (`order_ID` ASC) VISIBLE,
  CONSTRAINT `fk_cart_order1`
    FOREIGN KEY (`order_ID`)
    REFERENCES `u413142534_jaysnest`.`order` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `u413142534_jaysnest`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u413142534_jaysnest`.`employee` (
  `ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `u413142534_jaysnest`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u413142534_jaysnest`.`items` (
  `itemID` INT(11) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `weight` INT(11) NOT NULL,
  `price` INT(11) NOT NULL,
  `category` VARCHAR(45) NULL DEFAULT NULL,
  `ftype` VARCHAR(45) NULL DEFAULT NULL,
  `cartID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`itemID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `u413142534_jaysnest`.`robot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u413142534_jaysnest`.`robot` (
  `ID` INT(11) NOT NULL,
  `orderID` VARCHAR(45) NULL DEFAULT NULL,
  `destination` VARCHAR(45) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `order_ID` INT(11) NOT NULL,
  `employee_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`, `order_ID`),
  INDEX `fk_robot_order1_idx` (`order_ID` ASC) VISIBLE,
  INDEX `fk_robot_employee1_idx` (`employee_ID` ASC) VISIBLE,
  CONSTRAINT `fk_robot_employee1`
    FOREIGN KEY (`employee_ID`)
    REFERENCES `u413142534_jaysnest`.`employee` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_robot_order1`
    FOREIGN KEY (`order_ID`)
    REFERENCES `u413142534_jaysnest`.`order` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
